PythonVersion="3.11.15"
pythonBuildCommandsFile="/app/oryx-build-commands.txt"
virtualEnvName="antenv"
OperationId="7be6ba6e6ba98f8c"
SourceDirectoryInBuildContainer="/app"
PlatformName="python"
CompressDestinationDir="false"
